ALTER TABLE `role_perm`
ADD CONSTRAINT `rp_role` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT `rp_perm` FOREIGN KEY (`perm_id`) REFERENCES `perm` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
